rm(list=ls())
setwd("D:/Data Science/coursera/Course 4 - Exploratory Data Analysis/week 1/")
df <- read.table("household_power_consumption.txt", comment.char = "#", header = FALSE, sep = ";")
cnames <- readLines("household_power_consumption.txt",1)
cnames <- strsplit(cnames, ";", fixed = TRUE)
cnames
names(df) <- make.names(cnames [[1]])
df = df[-1,]
df$Date <- as.Date(df$Date, "%d/%m/%Y")
df <- subset(df, Date >= "2007-02-01")
df <- subset(df, Date <= "2007-02-02")
df$Sub_metering_1 <- as.numeric(as.character(df$Sub_metering_1))
df$Sub_metering_2 <- as.numeric(as.character(df$Sub_metering_2))
df$Sub_metering_3 <- as.numeric(as.character(df$Sub_metering_3))
df$datetime <- as.POSIXct(paste(df$Date, df$Time), format="%Y-%m-%d %H:%M:%S")
plot(df$datetime, df$Sub_metering_1, type = "l" , xlab='', ylab='Energy sub metering')
points(df$datetime, df$Sub_metering_2, col = "red", type = "l")
points(df$datetime, df$Sub_metering_3, col = "blue", type = "l")
legend("topright", pch = 1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png,'plot3.png')
dev.off()
